{
"grade":[
		{
			"value":1,
			"name":"小学",
			"nianji":[
				{
				  "value":1,"name":"小学一年级",
				  "subject":[
				       {"value":2464,"name":"语文"},
				       {"value":2466,"name":"英语"}
				  ]
				},
				{
				  "value":2,"name":"小学二年级",
				  "subject":[
				       {"value":2464,"name":"语文"},
				       {"value":2466,"name":"英语"}
				  ]
				}
			]
		},{
			"value":3,
			"name":"高中",
			"nianji":[
				{
				  "value":11,"name":"高中二年级",
				  "subject":[
				       {"value":2469,"name":"生物"},
				       {"value":2470,"name":"物理"}
				  ]
				},
				{
				  "value":12,"name":"高中三年级",
				  "subject":[
				       {"value":2469,"name":"生物"},
				       {"value":2470,"name":"物理"}
				  ]
				}
			]
		}		
	],
 "area":[
         {"value":110000,"name":"北京市"},
         {"value":210000,"name":"辽宁省"},
         {"value":810000,"name":"香港特别行政区"}
    ]
}

 